const state={lang:localStorage.getItem('zeta-lang')||'ar',site:null,products:[],brochures:[],news:[]};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pick=(ar,en)=>state.lang==='ar'?(ar||en||''):(en||ar||'');
async function json(path,fallback){try{const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw 0;return await r.json()}catch{return fallback}}
function applyLang(){document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-ar]').forEach(e=>e.textContent=pick(e.dataset.ar,e.dataset.en));$('#language').textContent=state.lang==='ar'?'EN':'عربي';const c=state.site?.company||{};const h=state.site?.home||{};$('#heroTitle').textContent=pick(h.heroTitleAr,h.heroTitleEn)||'حلول دوائية موثوقة';$('#heroText').textContent=pick(h.heroTextAr,h.heroTextEn)||'';$('#aboutText').textContent=pick(state.site?.about?.textAr,state.site?.about?.textEn)||$('#aboutText').dataset.ar;$('#phone').textContent=c.phone||'—';$('#whatsapp').textContent=c.whatsapp||'—';$('#email').textContent=c.email||'—';$('#address').textContent=pick(c.addressAr,c.addressEn)||'—';$('#topContact').textContent=c.phone||'';$('#phoneLink').href=c.phone?'tel:'+c.phone:'#';$('#whatsappLink').href=c.whatsapp?'https://wa.me/'+c.whatsapp.replace(/\D/g,''): '#';$('#emailLink').href=c.email?'mailto:'+c.email:'#';renderProducts(state.products);renderBrochures(state.brochures);renderNews(state.news)}
function renderProducts(items){const q=($('#productSearch')?.value||'').trim().toLowerCase();const data=items.filter(p=>!q||pick(p.nameAr,p.nameEn).toLowerCase().includes(q)||pick(p.activeIngredientAr,p.activeIngredientEn).toLowerCase().includes(q));const g=$('#productsGrid');if(!data.length){g.innerHTML='<div class="empty">'+(q?'لا توجد نتائج مطابقة.':'لا توجد منتجات مضافة حتى الآن.')+'</div>';return}g.innerHTML=data.map(p=>`<article class="card">${p.image?`<img class="card-image" src="${esc(p.image)}" alt="${esc(pick(p.nameAr,p.nameEn))}">`:'<div class="card-image"></div>'}<div class="card-body"><h3>${esc(pick(p.nameAr,p.nameEn))}</h3><div class="meta">${esc(pick(p.activeIngredientAr,p.activeIngredientEn))} ${esc(p.strength||'')}</div><p>${esc(pick(p.descriptionAr,p.descriptionEn))}</p><div class="card-actions">${p.brochure?`<a class="small-btn" href="${esc(p.brochure)}" target="_blank">Brochure</a>`:''}</div></div></article>`).join('')}
function renderBrochures(items){const g=$('#brochuresGrid');if(!items.length){g.innerHTML='<div class="empty">لا توجد بروشورات مضافة حتى الآن.</div>';return}g.innerHTML=items.map(b=>`<article class="card"><div class="card-body"><span class="kicker">PDF</span><h3>${esc(pick(b.titleAr,b.titleEn))}</h3><p>${esc(pick(b.descriptionAr,b.descriptionEn))}</p><div class="card-actions"><a class="small-btn" href="${esc(b.file)}" target="_blank">Open PDF</a></div></div></article>`).join('')}
function renderNews(items){const g=$('#newsGrid');if(!items.length){g.innerHTML='<div class="empty">لا توجد أخبار مضافة حتى الآن.</div>';return}g.innerHTML=items.map(n=>`<article class="card">${n.image?`<img class="card-image" src="${esc(n.image)}" alt="">`:''}<div class="card-body"><span class="meta">${esc(n.date||'')}</span><h3>${esc(pick(n.titleAr,n.titleEn))}</h3><p>${esc(pick(n.excerptAr,n.excerptEn))}</p></div></article>`).join('')}
$('#language').addEventListener('click',()=>{state.lang=state.lang==='ar'?'en':'ar';localStorage.setItem('zeta-lang',state.lang);applyLang()});$('#menu').addEventListener('click',()=>$('#nav').classList.toggle('open'));$('#productSearch').addEventListener('input',()=>renderProducts(state.products));
(async()=>{state.site=await json('content/site.json',{});state.products=await json('content/products.json',[]);state.brochures=await json('content/brochures.json',[]);state.news=await json('content/news.json',[]);$('#year').textContent=new Date().getFullYear();applyLang()})();
