const SESSION_COOKIE="zeta_admin_session";
const SESSION_TTL_SECONDS=28800;
const WORKER_VERSION="cms-github-2026-09-04-04";
const OWNER="saeedgmal6-tech";
const REPO="zeta-biotech";
const BRANCH="main";
const CONTENT=new Set(["site","products","brochures","news","certifications","jobs","leads","analytics"]);
const MAX_UPLOAD=10*1024*1024;
const MAX_JSON=2*1024*1024;

function b64e(v){const b=v instanceof Uint8Array?v:new TextEncoder().encode(v);let s="";for(let i=0;i<b.length;i++)s+=String.fromCharCode(b[i]);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function b64d(v){v=v.replace(/-/g,"+").replace(/_/g,"/");v+="=".repeat((4-v.length%4)%4);const s=atob(v),b=new Uint8Array(s.length);for(let i=0;i<s.length;i++)b[i]=s.charCodeAt(i);return b}
async function sign(secret,value){const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64e(new Uint8Array(await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(value))))}
function eq(a,b){if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0}
function cookie(req,name){for(const x of(req.headers.get("Cookie")||"").split(";")){const p=x.trim().indexOf("=");if(p>0&&x.trim().slice(0,p)===name)return decodeURIComponent(x.trim().slice(p+1))}return null}
async function session(req,env){const t=cookie(req,SESSION_COOKIE);if(!t||!env.SESSION_SECRET)return null;const p=t.split(".");if(p.length!==2||!eq(p[1],await sign(env.SESSION_SECRET,p[0])))return null;try{const x=JSON.parse(new TextDecoder().decode(b64d(p[0])));return x.exp>=Math.floor(Date.now()/1000)?x:null}catch{return null}}
function out(data,status=200,headers={}){return new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json;charset=utf-8","Cache-Control":"no-store","X-Zeta-Worker-Version":WORKER_VERSION,...headers}})}
function gh(env,path){return "https://api.github.com/repos/"+OWNER+"/"+REPO+"/contents/"+path.split("/").map(encodeURIComponent).join("/")}
function ghh(env){return {Authorization:"Bearer "+env.GITHUB_TOKEN,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","User-Agent":"Zeta-Biotech-CMS"}}
function pathName(p){p=String(p||"").replace(/^\/+/,"");if(p.startsWith("content/"))p=p.slice(8);if(p.endsWith(".json"))p=p.slice(0,-5);return CONTENT.has(p)?p:null}
function contentPath(p){return "content/"+p+".json"}
function b64(text){const bytes=new TextEncoder().encode(text);let s="";for(let i=0;i<bytes.length;i+=32768)s+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(s)}
async function getFile(env,path){const r=await fetch(gh(env,path)+"?ref="+BRANCH,{headers:ghh(env)});if(r.status===404)return{exists:false};if(!r.ok)return{error:"GitHub read failed.",status:r.status};const d=await r.json(),raw=atob(String(d.content||"").replace(/\n/g,""));const bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));return{exists:true,sha:d.sha,text:new TextDecoder().decode(bytes)}}
async function putFile(env,path,text,message,backup=true){const cur=await getFile(env,path);if(cur.error)return cur;if(backup&&cur.exists&&cur.text!==text){const safe=path.replace(/[^A-Za-z0-9._/-]/g,"_");const bp="content/backups/"+new Date().toISOString().replace(/[:.]/g,"-")+"-"+safe.split("/").pop();const br=await fetch(gh(env,bp),{method:"PUT",headers:{...ghh(env),"Content-Type":"application/json"},body:JSON.stringify({message:"CMS backup before update "+path,content:b64(cur.text),branch:BRANCH})});if(!br.ok)return{error:"Backup failed. The content was not changed.",status:502}}const body={message,content:b64(text),branch:BRANCH};if(cur.exists)body.sha=cur.sha;const r=await fetch(gh(env,path),{method:"PUT",headers:{...ghh(env),"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json().catch(()=>({}));return r.ok?{ok:true,commit:d.commit?.sha||null}:{error:d.message||"GitHub write failed.",status:r.status}}
async function adminContent(req,env,requested){const name=pathName(requested);if(!name)return out({ok:false,error:"Invalid content path."},400);if(!await session(req,env))return out({ok:false,error:"Unauthorized"},401);const path=contentPath(name);if(req.method==="GET"){const r=await getFile(env,path);if(r.error)return out({ok:false,error:r.error},r.status);if(!r.exists)return out({ok:true,data:null});try{return out({ok:true,data:JSON.parse(r.text)})}catch{return out({ok:false,error:"Stored JSON is invalid."},500)}}if(req.method!=="PUT")return out({ok:false,error:"Method not allowed"},405);let body;try{body=await req.json()}catch{return out({ok:false,error:"Invalid JSON."},400)}const data=Object.prototype.hasOwnProperty.call(body,"data")?body.data:body,text=JSON.stringify(data,null,2)+"\n";if(text.length>MAX_JSON)return out({ok:false,error:"Content is too large."},413);const r=await putFile(env,path,text,"CMS update "+path,true);return r.ok?out(r):out({ok:false,error:r.error},r.status)}
async function login(req,env){if(req.method!=="POST")return out({ok:false,error:"Method not allowed"},405);let b;try{b=await req.json()}catch{return out({ok:false,error:"Invalid request."},400)}const u=String(b.username||"").trim(),p=String(b.password||"");if(!env.ADMIN_USERNAME||!env.ADMIN_PASSWORD||!env.SESSION_SECRET)return out({ok:false,error:"Admin authentication is not configured in Cloudflare yet."},503);if(!eq(u,env.ADMIN_USERNAME)||!eq(p,env.ADMIN_PASSWORD))return out({ok:false,error:"Invalid username or password."},401);const payload=b64e(JSON.stringify({sub:u,exp:Math.floor(Date.now()/1000)+SESSION_TTL_SECONDS})),token=payload+"."+await sign(env.SESSION_SECRET,payload);return out({ok:true},200,{"Set-Cookie":SESSION_COOKIE+"="+encodeURIComponent(token)+"; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age="+SESSION_TTL_SECONDS})}
async function upload(req,env){if(!await session(req,env))return out({ok:false,error:"Unauthorized"},401);let b;try{b=await req.json()}catch{return out({ok:false,error:"Invalid JSON."},400)}const name=String(b.name||"").trim().replace(/[^A-Za-z0-9._-]/g,"_"),mime=String(b.mime||"").toLowerCase(),data=String(b.data||"");if(!name||!data)return out({ok:false,error:"File name and data are required."},400);if(!["image/png","image/jpeg","image/webp","image/svg+xml","application/pdf"].includes(mime)||!/\.(png|jpe?g|webp|svg|pdf)$/i.test(name))return out({ok:false,error:"Only PNG, JPG, WEBP, SVG and PDF files are allowed."},415);if(data.length*0.75>MAX_UPLOAD)return out({ok:false,error:"Maximum upload size is 10 MB."},413);const path="assets/uploads/"+Date.now()+"-"+name,r=await fetch(gh(env,path),{method:"PUT",headers:{...ghh(env),"Content-Type":"application/json"},body:JSON.stringify({message:"CMS upload "+name,content:data,branch:BRANCH})}),d=await r.json().catch(()=>({}));return r.ok?out({ok:true,path,url:"/"+path}):out({ok:false,error:d.message||"GitHub upload failed."},r.status)}
async function del(req,env){if(!await session(req,env))return out({ok:false,error:"Unauthorized"},401);const p=new URL(req.url).searchParams.get("path")||"";if(!/^assets\/uploads\/[A-Za-z0-9._-]+$/.test(p))return out({ok:false,error:"Invalid file path."},400);const cur=await getFile(env,p);if(cur.error)return out({ok:false,error:cur.error},cur.status);if(!cur.exists)return out({ok:true,deleted:false});const r=await fetch(gh(env,p),{method:"DELETE",headers:{...ghh(env),"Content-Type":"application/json"},body:JSON.stringify({message:"CMS delete "+p,sha:cur.sha,branch:BRANCH})});return r.ok?out({ok:true,deleted:true}):out({ok:false,error:"GitHub delete failed."},r.status)}
async function lead(req,env){if(req.method!=="POST")return out({ok:false,error:"Method not allowed"},405);let b;try{b=await req.json()}catch{return out({ok:false,error:"Invalid JSON."},400)}const x={id:crypto.randomUUID(),date:new Date().toISOString(),status:"New",name:String(b.name||"").trim().slice(0,120),company:String(b.company||"").trim().slice(0,160),email:String(b.email||"").trim().slice(0,180),phone:String(b.phone||"").trim().slice(0,80),subject:String(b.subject||"").trim().slice(0,180),message:String(b.message||"").trim().slice(0,4000),lang:String(b.lang||"ar").slice(0,5)};if(!x.name||!x.message)return out({ok:false,error:"Name and message are required."},400);const cur=await getFile(env,"content/leads.json");if(cur.error)return out({ok:false,error:cur.error},cur.status);let d={leads:[]};if(cur.exists)try{d=JSON.parse(cur.text)}catch{}if(!Array.isArray(d.leads))d.leads=[];d.leads.unshift(x);d.leads=d.leads.slice(0,1000);const r=await putFile(env,"content/leads.json",JSON.stringify(d,null,2)+"\n","New website contact lead",false);return r.ok?out({ok:true,id:x.id}):out({ok:false,error:r.error},r.status)}
async function analytics(req,env){if(req.method!=="POST")return out({ok:false,error:"Method not allowed"},405);let b;try{b=await req.json()}catch{return out({ok:false,error:"Invalid JSON."},400)}const type=String(b.type||"page").slice(0,20),id=String(b.id||b.path||"unknown").slice(0,180).replace(/[^A-Za-z0-9._\/-]/g,"_");const cur=await getFile(env,"content/analytics.json");if(cur.error)return out({ok:false,error:cur.error},cur.status);let d={pageViews:0,productViews:{},newsViews:{},brochureViews:{}};if(cur.exists)try{d=JSON.parse(cur.text)}catch{}d.productViews=d.productViews||{};d.newsViews=d.newsViews||{};d.brochureViews=d.brochureViews||{};if(type==="page")d.pageViews=Number(d.pageViews||0)+1;else if(type==="product")d.productViews[id]=Number(d.productViews[id]||0)+1;else if(type==="news")d.newsViews[id]=Number(d.newsViews[id]||0)+1;else if(type==="brochure")d.brochureViews[id]=Number(d.brochureViews[id]||0)+1;const r=await putFile(env,"content/analytics.json",JSON.stringify(d,null,2)+"\n","Website analytics update",false);return r.ok?out({ok:true}):out({ok:false,error:r.error},r.status)}
export default{async fetch(req,env){const u=new URL(req.url);if(u.pathname==="/api/health")return out({ok:true,worker:"zeta-biotech",version:WORKER_VERSION});if(u.pathname==="/api/leads")return lead(req,env);if(u.pathname==="/api/analytics")return analytics(req,env);if(u.pathname==="/api/admin/login")return login(req,env);if(u.pathname==="/api/admin/me"){const s=await session(req,env);return s?out({authenticated:true,username:s.sub,expiresAt:s.exp}):out({authenticated:false},401)}if(u.pathname==="/api/admin/logout")return out({ok:true},200,{"Set-Cookie":SESSION_COOKIE+"=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0"});if(u.pathname.startsWith("/api/admin/content/"))return adminContent(req,env,u.pathname.slice(19));if(u.pathname==="/api/admin/upload")return upload(req,env);if(u.pathname==="/api/admin/file")return del(req,env);if(u.pathname==="/admin"||u.pathname==="/admin/"||u.pathname==="/admin/index.html"){if(!await session(req,env))return Response.redirect(new URL("/admin/login.html",req.url),302)}return env.ASSETS.fetch(req)}};