(function(){
'use strict';
var SOURCES=['site','products','brochures','news','certifications','jobs','faqs','testimonials'];
var db={site:{},products:[],brochures:[],news:[],certifications:[],jobs:[],faqs:[],testimonials:[]};
var history=[];
var ALIASES={contact:['تواصل','اتصال','التواصل','whatsapp','واتساب','واتس','هاتف','تليفون','موبايل','phone','email','ايميل','إيميل','بريد','خريطة','خرائط','maps','عنوان','location'],product:['منتج','منتجات','product','products','دواء','ادوية','أدوية','medicine','medicines'],brochure:['بروشور','بروشورات','brochure','brochures','pdf','كتالوج','كتالوجات','ملف'],news:['خبر','اخبار','أخبار','news','تحديث','تحديثات'],certification:['شهادة','شهادات','جودة','اعتماد','اعتمادات','certification','certifications','quality'],job:['وظيفة','وظائف','توظيف','وظائف شاغرة','job','jobs','career','careers'],distributor:['موزع','موزعين','توزيع','وكيل','وكلاء','distributor','distribution'],company:['شركة','الشركة','عن الشركة','نبذة','company','about','profile'],price:['سعر','السعر','اسعار','أسعار','price','pricing','cost'],ingredient:['المادة الفعالة','مادة فعالة','active ingredient','ingredient'],strength:['تركيز','التركيز','strength','concentration'],indication:['استخدام','استخدامات','دواعي الاستعمال','indication','indications','uses'],pack:['عبوة','العبوة','حجم العبوة','pack size','package']};
function ar(){return (localStorage.getItem('zeta-lang')||'ar')==='ar';}
function pick(a,e){return ar()?(a||e||''):(e||a||'');}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function norm(v){return String(v==null?'').toLowerCase().replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').replace(/[ًٌٍَُِّْـ]/g,'').replace(/[\u200f\u200e]/g,'').replace(/[^\p{L}\p{N}]+/gu,' ').trim();}
function tokens(q){return norm(q).split(/\s+/).filter(function(x){return x.length>1;});}
function textOf(v){var a=[];function walk(x){if(x==null)return;if(typeof x==='string'||typeof x==='number'||typeof x==='boolean'){a.push(String(x));return;}if(Array.isArray(x)){x.forEach(walk);return;}if(typeof x==='object')Object.keys(x).forEach(function(k){if(k!=='hidden')walk(x[k]);});}walk(v);return a.join(' ');}
function active(v){return Array.isArray(v)?v.filter(function(x){return x&&!x.hidden;}):[];}
function get(name){return fetch('/content/'+name+'.json?v='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.json():{};}).catch(function(){return{};});}
async function load(){var a=await Promise.all(SOURCES.map(get));db.site=a[0]||{};db.products=active((a[1]||{}).products);db.brochures=active((a[2]||{}).brochures);db.news=active((a[3]||{}).news);db.certifications=active((a[4]||{}).certifications);db.jobs=active((a[5]||{}).jobs);db.faqs=active((a[6]||{}).faqs);db.testimonials=active((a[7]||{}).testimonials);return db;}
function has(q,k){var n=norm(q);return ALIASES[k].some(function(x){return n.indexOf(norm(x))>=0;});}
function intent(q){return {contact:has(q,'contact'),product:has(q,'product'),brochure:has(q,'brochure'),news:has(q,'news'),certification:has(q,'certification'),job:has(q,'job'),distributor:has(q,'distributor'),company:has(q,'company'),price:has(q,'price'),ingredient:has(q,'ingredient'),strength:has(q,'strength'),indication:has(q,'indication'),pack:has(q,'pack')};}
function add(r,type,title,obj){var raw=textOf(obj);if(raw)r.push({type:type,title:title||'',raw:raw,source:obj});}
function records(){var r=[],c=db.site.company||{};add(r,'company','ZETA BIOTECH',db.site);add(r,'contact','بيانات التواصل',{name:c.name||'ZETA BIOTECH',phone:c.phone,whatsapp:c.whatsapp,email:c.email,address:c.address,addressAr:c.addressAr,addressEn:c.addressEn,googleMaps:c.googleMaps,facebook:c.facebook,instagram:c.instagram,linkedin:c.linkedin,overview:c.overview,overviewAr:c.overviewAr,overviewEn:c.overviewEn});db.products.forEach(function(x){add(r,'product',x.nameAr||x.nameEn||x.name||'Product',x);});db.brochures.forEach(function(x){add(r,'brochure',x.titleAr||x.titleEn||x.title||'Brochure',x);});db.news.forEach(function(x){add(r,'news',x.titleAr||x.titleEn||x.title||'News',x);});db.certifications.forEach(function(x){add(r,'certification',x.titleAr||x.titleEn||x.title||'Certification',x);});db.jobs.forEach(function(x){add(r,'job',x.titleAr||x.titleEn||x.title||'Job',x);});db.faqs.forEach(function(x){add(r,'faq',x.questionAr||x.questionEn||x.question||'FAQ',x);});db.testimonials.forEach(function(x){add(r,'testimonial',x.name||x.title||'Testimonial',x);});return r;}
function score(x,q){var n=norm(q),ts=tokens(q),t=norm(x.title+' '+x.raw),title=norm(x.title),s=0;if(n.length>3&&t.indexOf(n)>=0)s+=30;if(n.length>3&&title.indexOf(n)>=0)s+=45;ts.forEach(function(z){if(t.indexOf(z)>=0)s+=3;if(title.indexOf(z)>=0)s+=8;});return s;}
function empty(type){var m={product:['لا توجد منتجات منشورة حاليًا في قاعدة بيانات الموقع.','No products are currently published in the website database.'],brochure:['لا توجد بروشورات منشورة حاليًا.','No brochures are currently published.'],news:['لا توجد أخبار منشورة حاليًا.','No news items are currently published.'],certification:['لا توجد شهادات أو اعتمادات منشورة حاليًا.','No certifications are currently published.'],job:['لا توجد وظائف شاغرة منشورة حاليًا.','No job vacancies are currently published.'],faq:['لا توجد أسئلة شائعة منشورة حاليًا.','No FAQs are currently published.']};return m[type]?pick(m[type][0],m[type][1]):'';}
function contactAnswer(){var c=db.site.company||{},r=[];if(c.phone)r.push((ar()?'الهاتف: ':'Phone: ')+esc(c.phone));if(c.whatsapp)r.push((ar()?'WhatsApp: ':'WhatsApp: ')+esc(c.whatsapp));if(c.email)r.push((ar()?'البريد الإلكتروني: ':'Email: ')+esc(c.email));var a=c.addressAr||c.addressEn||c.address;if(a){if(typeof a==='object')a=pick(a.ar,a.en);r.push((ar()?'العنوان: ':'Address: ')+esc(a));}if(c.googleMaps)r.push('<a href="'+esc(c.googleMaps)+'" target="_blank" rel="noopener">'+(ar()?'فتح موقع الشركة على الخريطة ↗':'Open company location ↗')+'</a>');return r.length?r.join('<br>'):(ar()?'بيانات التواصل لم تُضف بعد في قاعدة بيانات الموقع.':'Contact details have not been added to the website database yet.');}
function productAnswer(s){var r=[],n=pick(s.nameAr,s.nameEn)||s.name;if(n)r.push('<b>'+esc(n)+'</b>');var d=pick(s.descriptionAr,s.descriptionEn);if(d)r.push(esc(d));if(s.activeIngredientAr||s.activeIngredientEn)r.push((ar()?'المادة الفعالة: ':'Active ingredient: ')+esc(pick(s.activeIngredientAr,s.activeIngredientEn)));if(s.strength)r.push((ar()?'التركيز: ':'Strength: ')+esc(s.strength));if(s.dosageForm)r.push((ar()?'الشكل الدوائي: ':'Dosage form: ')+esc(s.dosageForm));if(s.packSize)r.push((ar()?'العبوة: ':'Pack size: ')+esc(s.packSize));if(s.registrationNo)r.push((ar()?'رقم التسجيل: ':'Registration no.: ')+esc(s.registrationNo));if(s.indicationAr||s.indicationEn)r.push((ar()?'الاستخدامات: ':'Indications: ')+esc(pick(s.indicationAr,s.indicationEn)));return r.join('<br>');}
function textAnswer(x){var s=x.source||{};if(x.type==='product')return productAnswer(s);var t=pick(s.descriptionAr,s.descriptionEn)||pick(s.bodyAr,s.bodyEn)||pick(s.textAr,s.textEn)||pick(s.answerAr,s.answerEn)||pick(s.overviewAr,s.overviewEn)||pick(s.overview&&s.overview.ar,s.overview&&s.overview.en);return t?esc(t):'<b>'+esc(x.title)+'</b><br>'+esc(x.raw.slice(0,600));}
function answer(q){var i=intent(q),r=records();if(i.distributor)return ar()?'للتوزيع، استخدم قسم «كن موزعًا معتمدًا» لإرسال بيانات شركتك وبدء التواصل التجاري.':'For distribution, use the “Become an Authorized Distributor” section to submit your company details.';if(i.contact)return contactAnswer();var wanted=[];if(i.product)wanted.push('product');if(i.brochure)wanted.push('brochure');if(i.news)wanted.push('news');if(i.certification)wanted.push('certification');if(i.job)wanted.push('job');if(i.company)wanted.push('company');if(i.price){if(i.product)wanted=['product'];else return ar()?'أسعار المنتجات غير منشورة حاليًا. اكتب اسم المنتج الذي تقصده وسأبحث عنه.':'Product prices are not currently published. Type the product name you mean and I will search for it.';}if(wanted.length){var m=r.filter(function(x){return wanted.indexOf(x.type)>=0;});if(!m.length)return empty(wanted[0]);var ranked=m.map(function(x){return {x:x,s:score(x,q)};}).sort(function(a,b){return b.s-a.s;});if(wanted.length===1&&ranked[0].s>0)return textAnswer(ranked[0].x);return ranked.slice(0,10).map(function(v){return '• <b>'+esc(v.x.title)+'</b>';}).join('<br>');}var ranked=r.map(function(x){return {x:x,s:score(x,q)};}).filter(function(v){return v.s>0;}).sort(function(a,b){return b.s-a.s;});if(!ranked.length)return ar()?'لم أجد هذه المعلومة في قاعدة بيانات ZETA BIOTECH الحالية. جرّب اسم المنتج أو الموضوع بشكل أوضح.':'I could not find this information in the current ZETA BIOTECH database. Try a product name or clearer topic.';return textAnswer(ranked[0].x);}
function ensure(){var host=document.getElementById('znextAssistant');if(!host){host=document.createElement('div');host.id='znextAssistant';host.className='znext-assistant';document.body.appendChild(host);}if(host.dataset.zetaDbAI==='1')return;host.dataset.zetaDbAI='1';host.innerHTML='<div class="znext-ai-panel" id="znextAiPanel"><div class="znext-ai-head">🤖 ZETA BIOTECH AI</div><div class="znext-ai-body" id="znextAiBody"><div class="znext-ai-msg">'+(ar()?'مرحبًا! أنا مساعد ZETA BIOTECH. كل إجابة أبحث عنها مباشرة في قاعدة بيانات الموقع.':'Hello! I am the ZETA BIOTECH assistant. I search the website database directly for every answer.')+'</div></div><form class="znext-ai-form" id="znextAiForm"><input id="znextAiInput" autocomplete="off" placeholder="'+(ar()?'اكتب سؤالك...':'Ask a question...')+'"><button type="submit">↗</button></form></div><button class="znext-ai-btn" id="znextAiBtn">🤖 '+(ar()?'المساعد الذكي':'AI Assistant')+'</button>';document.getElementById('znextAiBtn').onclick=function(){document.getElementById('znextAiPanel').classList.toggle('show');};document.getElementById('znextAiForm').onsubmit=async function(e){e.preventDefault();var input=document.getElementById('znextAiInput'),q=String(input.value||'').trim();if(!q)return;var body=document.getElementById('znextAiBody');body.innerHTML+='<div class="znext-ai-msg znext-ai-user">'+esc(q)+'</div>';input.value='';try{await load();var a=answer(q);history.push({q:q,a:a});if(history.length>10)history.shift();body.innerHTML+='<div class="znext-ai-msg">'+a+'</div>';}catch(err){body.innerHTML+='<div class="znext-ai-msg">'+(ar()?'حدث خطأ أثناء قراءة قاعدة البيانات. حاول مرة أخرى.':'A database read error occurred. Please try again.')+'</div>';}body.scrollTop=body.scrollHeight;};}
function boot(){load().then(ensure).catch(ensure);setTimeout(load,2500);setInterval(load,30000);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();