(function(){'use strict';
var s=document.createElement('script');
s.src='/zeta-ai-core.js?v=20260905';
s.defer=true;
document.head.appendChild(s);
var p=document.createElement('script');
p.src='/zeta-ai-navigation-polish.js?v=20260905';
p.defer=true;
document.head.appendChild(p);
})();