(function(){
  function ready(fn){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',fn);else fn()}
  function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
  async function api(path,opts){var r=await fetch(path,Object.assign({headers:{'Content-Type':'application/json'}},opts||{}));var d=await r.json().catch(function(){return{}});if(!r.ok||d.ok===false)throw new Error(d.error||'Request failed');return d}
  ready(function(){
    var host=document.querySelector('main')||document.body;
    if(document.getElementById('zetaAdvancedAdmin'))return;
    var box=document.createElement('section');box.id='zetaAdvancedAdmin';box.style.cssText='margin:24px 0;padding:24px;border:1px solid #dbe5ea;border-radius:18px;background:#fff;box-shadow:0 10px 35px rgba(7,27,43,.07)';
    box.innerHTML='<div style="display:flex;gap:10px;flex-wrap:wrap;margin-bottom:18px"><button data-tab="analytics">Analytics</button><button data-tab="leads">Leads</button><button data-tab="quality">Quality & Certifications</button><button data-tab="jobs">Careers</button><button data-tab="history">Backup / History</button></div><div id="zetaAdvancedBody"></div>';
    host.appendChild(box);
    var body=box.querySelector('#zetaAdvancedBody');
    function panel(title,html){body.innerHTML='<h2>'+title+'</h2>'+html}
    async function analytics(){
      var d=await api('/api/admin/content/analytics');var a=d.data||{};
      var pv=Number(a.pageViews||0),products=a.productViews||{},news=a.newsViews||{},brochures=a.brochureViews||{};
      var pageRows=Object.keys(products).filter(function(k){return k.indexOf('__page__')===0}).sort(function(x,y){return Number(products[y]||0)-Number(products[x]||0)});
      var realProducts=Object.keys(products).filter(function(k){return k.indexOf('__page__')!==0});
      var pageHtml=pageRows.length?pageRows.map(function(k){var path=k.slice(8)||'/';return '<tr><td dir="ltr"><a href="'+esc(path)+'" target="_blank" rel="noopener">'+esc(path)+'</a></td><td>'+esc(products[k]||0)+'</td></tr>'}).join(''):'<tr><td colspan="2">لا توجد صفحات مسجلة بعد.</td></tr>';
      panel('Analytics','<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px"><div class="card"><b>إجمالي الزيارات</b><div style="font-size:30px">'+esc(pv)+'</div></div><div class="card"><b>الصفحات المسجلة</b><div style="font-size:30px">'+esc(pageRows.length)+'</div></div><div class="card"><b>Product Views</b><div style="font-size:30px">'+esc(realProducts.reduce(function(x,k){return x+Number(products[k]||0)},0))+'</div></div><div class="card"><b>News Views</b><div style="font-size:30px">'+esc(Object.values(news).reduce(function(x,y){return x+Number(y||0)},0))+'</div></div><div class="card"><b>Brochure Opens</b><div style="font-size:30px">'+esc(Object.values(brochures).reduce(function(x,y){return x+Number(y||0)},0))+'</div></div></div><div style="margin-top:22px"><h3>الزوار دخلوا على أنهي لينك؟</h3><div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th style="text-align:right">الرابط / الصفحة</th><th style="text-align:right">عدد الزيارات</th></tr></thead><tbody>'+pageHtml+'</tbody></table></div></div><p style="margin-top:18px">يتم تسجيل الزيارات تلقائيًا من الموقع العام على Worker الحالي، مع حفظ مسار الصفحة التي تمت زيارتها.</p>')
    }
    async function leads(){var d=await api('/api/admin/content/leads');var rows=(d.data&&d.data.leads)||[];panel('Contact Leads','<div style="overflow:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th>Date</th><th>Name</th><th>Company</th><th>Contact</th><th>Subject</th><th>Status</th></tr></thead><tbody>'+rows.map(function(x,i){return '<tr><td>'+esc(x.date||'')+'</td><td>'+esc(x.name)+'</td><td>'+esc(x.company)+'</td><td>'+esc(x.email||'')+'<br>'+esc(x.phone||'')+'</td><td>'+esc(x.subject||'')+'<br>'+esc(x.message||'')+'</td><td><select data-lead="'+i+'"><option '+(x.status==='New'?'selected':'')+'>New</option><option '+(x.status==='Contacted'?'selected':'')+'>Contacted</option><option '+(x.status==='Closed'?'selected':'')+'>Closed</option></select></td></tr>'}).join('')+'</tbody></table></div>');body.querySelectorAll('[data-lead]').forEach(function(s){s.addEventListener('change',async function(){var idx=Number(s.dataset.lead),d=await api('/api/admin/content/leads'),arr=d.data||{leads:[]};arr.leads[idx].status=s.value;await api('/api/admin/content/leads',{method:'PUT',body:JSON.stringify({data:arr})})})})}
    async function quality(){var d=await api('/api/admin/content/certifications');var rows=(d.data&&d.data.certifications)||[];panel('Quality & Certifications','<form id="certForm" style="display:grid;gap:10px;max-width:700px"><input name="titleAr" placeholder="اسم الشهادة بالعربي" required><input name="titleEn" placeholder="Certificate title in English"><textarea name="descriptionAr" placeholder="الوصف بالعربي"></textarea><textarea name="descriptionEn" placeholder="Description in English"></textarea><input name="file" placeholder="PDF/Image URL"><button type="submit">Add Certification</button></form><hr><div>'+rows.map(function(x,i){return '<div style="padding:12px;border-bottom:1px solid #eee"><b>'+esc(x.titleAr||x.titleEn)+'</b><button data-cert="'+i+'" style="float:right">Delete</button><p>'+esc(x.descriptionAr||x.descriptionEn)+'</p></div>'}).join('')+'</div>');body.querySelector('#certForm').onsubmit=async function(e){e.preventDefault();var f=new FormData(e.target),d=await api('/api/admin/content/certifications'),arr=d.data||{certifications:[]};arr.certifications.push({id:Date.now().toString(),titleAr:f.get('titleAr'),titleEn:f.get('titleEn'),descriptionAr:f.get('descriptionAr'),descriptionEn:f.get('descriptionEn'),file:f.get('file'),hidden:false});await api('/api/admin/content/certifications',{method:'PUT',body:JSON.stringify({data:arr})});quality()};body.querySelectorAll('[data-cert]').forEach(function(b){b.onclick=async function(){var d=await api('/api/admin/content/certifications'),arr=d.data||{certifications:[]};arr.certifications.splice(Number(b.dataset.cert),1);await api('/api/admin/content/certifications',{method:'PUT',body:JSON.stringify({data:arr})});quality()}})}
    async function jobs(){var d=await api('/api/admin/content/jobs');var rows=(d.data&&d.data.jobs)||[];panel('Careers','<form id="jobForm" style="display:grid;gap:10px;max-width:700px"><input name="titleAr" placeholder="المسمى الوظيفي بالعربي" required><input name="titleEn" placeholder="Job title in English"><textarea name="descriptionAr" placeholder="الوصف بالعربي"></textarea><textarea name="descriptionEn" placeholder="Description in English"></textarea><input name="locationAr" placeholder="الموقع بالعربي"><input name="locationEn" placeholder="Location in English"><input name="type" placeholder="Full-time / Part-time"><input name="email" type="email" placeholder="Applications email"><button type="submit">Add Job</button></form><hr><div>'+rows.map(function(x,i){return '<div style="padding:12px;border-bottom:1px solid #eee"><b>'+esc(x.titleAr||x.titleEn)+'</b> — '+esc(x.locationAr||x.locationEn)+'<button data-job="'+i+'" style="float:right">Delete</button></div>'}).join('')+'</div>');body.querySelector('#jobForm').onsubmit=async function(e){e.preventDefault();var f=new FormData(e.target),d=await api('/api/admin/content/jobs'),arr=d.data||{jobs:[]};arr.jobs.push({id:Date.now().toString(),titleAr:f.get('titleAr'),titleEn:f.get('titleEn'),descriptionAr:f.get('descriptionAr'),descriptionEn:f.get('descriptionEn'),locationAr:f.get('locationAr'),locationEn:f.get('locationEn'),type:f.get('type'),email:f.get('email'),hidden:false});await api('/api/admin/content/jobs',{method:'PUT',body:JSON.stringify({data:arr})});jobs()};body.querySelectorAll('[data-job]').forEach(function(b){b.onclick=async function(){var d=await api('/api/admin/content/jobs'),arr=d.data||{jobs:[]};arr.jobs.splice(Number(b.dataset.job),1);await api('/api/admin/content/jobs',{method:'PUT',body:JSON.stringify({data:arr})});jobs()}})}
    async function history(){var d=await api('/api/admin/content/site');panel('Backup / History','<p>Every CMS content update creates a timestamped backup in <code>content/backups/</code> before the new version is committed.</p><p>Current site content loaded successfully: '+esc(!!d.data)+'</p><p>Use the GitHub repository history to restore any previous committed version if required.</p>')}
    box.querySelectorAll('[data-tab]').forEach(function(b){b.onclick=function(){var t=b.dataset.tab;(t==='analytics'?analytics:t==='leads'?leads:t==='quality'?quality:t==='jobs'?jobs:history)().catch(function(e){panel('Error','<p>'+esc(e.message)+'</p>')})}});analytics().catch(function(){panel('Advanced Admin','<p>Advanced administration is loading. Refresh if the API is still starting.</p>')});
  })
})();
