(function(){
'use strict';
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
async function get(path){try{var r=await fetch(path,{cache:'no-store',headers:{'Content-Type':'application/json'}});return r.ok?await r.json():{};}catch(e){return{}}}
function classify(x){var s=String((x&&x.subject)||'')+' '+String((x&&x.message)||'');if(/Distributor Application|طلب موزع|كن موزع|موزع/i.test(s))return 'طلب توزيع';if(/Product Inquiry|استفسار عن المنتج|استفسار منتج/i.test(s))return 'استفسار منتج';return 'رسالة تواصل'}
function boot(){var top=document.querySelector('.topin');if(!top)return;var old=document.getElementById('zetaReliableNotifications');if(old)old.remove();var wrap=document.createElement('div');wrap.id='zetaReliableNotifications';wrap.style.cssText='position:relative;display:inline-block;margin-left:10px';wrap.innerHTML='<button id="zetaReliableBtn" style="border:1px solid #78909a;background:#071b2b;color:#fff;padding:9px 14px;border-radius:9px;cursor:pointer;font-weight:900;position:relative">🔔 مركز الإشعارات <span id="zetaReliableBadge" style="position:absolute;top:-8px;left:-8px;min-width:21px;height:21px;padding:0 5px;border-radius:999px;background:#d92d20;color:#fff;font-size:11px;display:none;align-items:center;justify-content:center">0</span></button><div id="zetaReliableMenu" style="display:none;position:absolute;top:48px;left:0;width:430px;max-width:calc(100vw - 28px);max-height:70vh;overflow:auto;background:#fff;color:#17212b;border:1px solid #dce5e8;border-radius:14px;box-shadow:0 16px 50px rgba(0,0,0,.2);padding:10px;z-index:99999"><div style="display:flex;justify-content:space-between;align-items:center;padding:7px 8px 12px"><b>كل الرسائل والطلبات</b><button id="zetaReliableRefresh" style="border:0;border-radius:8px;padding:6px 9px;cursor:pointer">تحديث</button></div><div id="zetaReliableList"></div></div>';var logout=document.getElementById('logout');top.insertBefore(wrap,logout||null);var btn=document.getElementById('zetaReliableBtn'),menu=document.getElementById('zetaReliableMenu');btn.onclick=function(e){e.stopPropagation();menu.style.display=menu.style.display==='block'?'none':'block';if(menu.style.display==='block')refresh()};document.addEventListener('click',function(e){if(!wrap.contains(e.target))menu.style.display='none'});document.getElementById('zetaReliableRefresh').onclick=refresh;refresh();setInterval(refresh,15000)}
async function refresh(){var l=await get('/api/admin/content/leads'),a=await get('/api/admin/content/job-applications'),leads=l.data&&Array.isArray(l.data.leads)?l.data.leads:[],apps=a.data&&Array.isArray(a.data.applications)?a.data.applications:[],items=[];leads.forEach(function(x){items.push({id:'lead:'+x.id,type:classify(x),name:x.name||'عميل',subject:x.subject||'',message:x.message||'',contact:(x.phone||'')+(x.email?' — '+x.email:''),date:x.date||''})});apps.forEach(function(x){items.push({id:'app:'+x.id,type:'طلب توظيف',name:x.name||'متقدم',subject:x.jobTitle||'',message:x.message||'',contact:(x.phone||'')+(x.email?' — '+x.email:''),date:x.date||'',cv:x.cvUrl||''})});items.sort(function(a,b){return String(b.date).localeCompare(String(a.date))});var badge=document.getElementById('zetaReliableBadge'),list=document.getElementById('zetaReliableList');if(!badge||!list)return;var seen=JSON.parse(localStorage.getItem('zeta-reliable-read')||'{}'),unread=items.filter(function(x){return !seen[x.id]});badge.textContent=unread.length>99?'99+':String(unread.length);badge.style.display=unread.length?'flex':'none';list.innerHTML=items.slice(0,60).map(function(x){return '<div data-rid="'+esc(x.id)+'" style="padding:12px 9px;border-bottom:1px solid #edf1f2;cursor:pointer;'+(seen[x.id]?'opacity:.58':'font-weight:800')+'"><div style="display:flex;justify-content:space-between;gap:8px"><b>'+esc(x.type)+'</b><small>'+esc(x.date)+'</small></div><div>'+esc(x.name)+' '+(x.subject?' — '+esc(x.subject):'')+'</div><div style="color:#66727d;margin-top:4px">'+esc(x.contact)+'</div><div style="margin-top:5px;white-space:pre-wrap">'+esc(x.message)+'</div>'+(x.cv?'<a target="_blank" rel="noopener" href="'+esc(x.cv)+'">CV</a>':'')+'</div>'}).join('')||'<div style="padding:24px;text-align:center;color:#66727d">لا توجد رسائل أو طلبات حاليًا</div>';list.querySelectorAll('[data-rid]').forEach(function(el){el.onclick=function(){seen[el.dataset.rid]=true;localStorage.setItem('zeta-reliable-read',JSON.stringify(seen));refresh()}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(boot,100)});else boot();
})();
